import React, { useState } from 'react';
import { X, Copy, Check, FileText } from 'lucide-react';
import { DecisionAnalysis } from '../types';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  analysis: DecisionAnalysis;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, analysis }) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  // Generate Markdown string
  const markdownContent = `# Decision Analysis: ${analysis.title}

## Summary
${analysis.summary}

## The Tie Breaker Verdict: ${analysis.verdict.winnerName} (${analysis.verdict.confidencePercentage}% Confidence)
> "${analysis.verdict.headline}"

### Recommendation
${analysis.verdict.detailedRecommendation}

### Key Blind Spots & Risks
${analysis.verdict.blindSpots.map((b) => `- ${b}`).join('\n')}

---

## Pros & Cons Breakdown

${analysis.options
  .map(
    (opt) => `### Option: ${opt.name}
*${opt.tagline}*

**Pros:**
${opt.pros.map((p) => `- [${p.category}] ${p.text} (+${p.importance} pts)`).join('\n')}

**Cons:**
${opt.cons.map((c) => `- [${c.category}] ${c.text} (-${c.severity} pts)`).join('\n')}
`
  )
  .join('\n')}

---
*Generated by The Tie Breaker AI Strategist*
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4 font-sans">
      <div className="bg-white border-2 border-black max-w-2xl w-full max-h-[85vh] flex flex-col shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] overflow-hidden animate-in zoom-in-95 duration-150">
        {/* Modal Header */}
        <div className="p-5 border-b-2 border-black flex items-center justify-between bg-black text-white">
          <div className="flex items-center space-x-2">
            <FileText className="w-5 h-5 text-white" />
            <h3 className="font-serif font-black text-white text-xl uppercase tracking-tight">Export Strategic Brief</h3>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 text-white hover:text-gray-300 transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body: Markdown Preview */}
        <div className="p-5 overflow-y-auto flex-1 font-mono text-xs text-[#1C1C1C] bg-[#F9F7F2] border-b border-black leading-relaxed whitespace-pre-wrap select-all">
          {markdownContent}
        </div>

        {/* Modal Footer */}
        <div className="p-4 bg-white flex items-center justify-end space-x-3">
          <button
            onClick={onClose}
            className="px-4 py-2 text-xs font-sans font-bold uppercase tracking-widest text-black border border-black hover:bg-gray-100"
          >
            Close
          </button>

          <button
            onClick={handleCopy}
            className="px-5 py-2.5 bg-black text-white hover:bg-gray-800 font-sans font-bold text-xs uppercase tracking-widest flex items-center space-x-2 shadow-[2px_2px_0px_0px_rgba(0,0,0,0.3)] transition"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-emerald-400" />
                <span>Copied to Clipboard!</span>
              </>
            ) : (
              <>
                <Copy className="w-4 h-4 text-white" />
                <span>Copy Markdown Brief</span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};
